import citadel from "@/../data/paints/citadel.json";
import vallejo from "@/../data/paints/vallejo.json";
import akInteractive from "@/../data/paints/ak-interactive.json";
import armyPainter from "@/../data/paints/army-painter.json";
import duncanRhodes from "@/../data/paints/duncan-rhodes.json";
import greenStuffWorld from "@/../data/paints/green-stuff-world.json";
import liquitex from "@/../data/paints/liquitex.json";
import mig from "@/../data/paints/mig.json";
import p3 from "@/../data/paints/p3.json";
import scale75 from "@/../data/paints/scale-75.json";
import tamiya from "@/../data/paints/tamiya.json";

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { hexToLab, hueFamily } from "@/lib/color";
import type { Paint, PaintWithLab } from "./types";

const RAW: Paint[] = [
  ...(citadel as Paint[]),
  ...(vallejo as Paint[]),
  ...(akInteractive as Paint[]),
  ...(armyPainter as Paint[]),
  ...(duncanRhodes as Paint[]),
  ...(greenStuffWorld as Paint[]),
  ...(liquitex as Paint[]),
  ...(mig as Paint[]),
  ...(p3 as Paint[]),
  ...(scale75 as Paint[]),
  ...(tamiya as Paint[]),
];

let cache: PaintWithLab[] | null = null;

/** All paints, enriched with precomputed Lab + colour family. Memoized. */
export function getAllPaints(): PaintWithLab[] {
  if (cache) return cache;
  cache = RAW.map((p) => ({
    ...p,
    lab: hexToLab(p.hex),
    family: hueFamily(p.hex),
  }));
  return cache;
}

/** Look up a single paint by id. */
export function getPaintById(id: string): PaintWithLab | undefined {
  return getAllPaints().find((p) => p.id === id);
}

/** Distinct brands, sorted. */
export function getBrands(): string[] {
  return [...new Set(getAllPaints().map((p) => p.brand))].sort();
}

let byIdCache: Map<string, PaintWithLab> | null = null;
function getPaintMap(): Map<string, PaintWithLab> {
  if (!byIdCache) {
    byIdCache = new Map(getAllPaints().map((p) => [p.id, p]));
  }
  return byIdCache;
}

/** A precomputed similar-colour match (resolved to the full paint record). */
export interface SimilarMatch {
  paint: PaintWithLab;
  distance: number;
}

interface SimilarRef {
  id: string;
  d: number;
}
type SimilarIndex = Record<string, { all: SimilarRef[]; cross: SimilarRef[] }>;

let similarCache: SimilarIndex | null = null;
function getSimilarIndex(): SimilarIndex {
  if (!similarCache) {
    // Generated by `npm run build:similar-index` (see prebuild/predev). Read at
    // build time only — every paint page is statically prerendered.
    const path = join(process.cwd(), ".cache", "similar-index.json");
    similarCache = JSON.parse(readFileSync(path, "utf8")) as SimilarIndex;
  }
  return similarCache;
}

/**
 * Precomputed nearest colours for a paint: `all` across every brand and `cross`
 * excluding the paint's own brand. Resolves the stored ids to full records and
 * silently drops any that are no longer present.
 */
export function getSimilarColours(id: string): {
  all: SimilarMatch[];
  cross: SimilarMatch[];
} {
  const record = getSimilarIndex()[id];
  if (!record) return { all: [], cross: [] };
  const byId = getPaintMap();
  const resolve = (refs: SimilarRef[]): SimilarMatch[] =>
    refs
      .map((r) => {
        const paint = byId.get(r.id);
        return paint ? { paint, distance: r.d } : null;
      })
      .filter((m): m is SimilarMatch => m !== null);
  return { all: resolve(record.all), cross: resolve(record.cross) };
}
